export const QA003 = [
  ["Windows 기본 명령어 중 현재 디렉터리의 파일 목록을 표시하는 명령어", "DIR"],
  ["Windows 기본 명령어 중 DIR의 기능", "현재 디렉터리의 파일 목록을 표시함"],
  ["Windows 기본 명령어 중 파일을 복사하는 명령어", "COPY"],
  ["Windows 기본 명령어 중 COPY의 기능", "파일을 복사함"],
  ["Windows에서 abc.txt 파일을 forder 디렉터리로 복사하는 명령문", "copy abc.txt forder"],
  ["Windows 기본 명령어 중 파일을 삭제하는 명령어", "DEL"],
  ["Windows 기본 명령어 중 DEL의 기능", "파일을 삭제함"],
  ["Windows에서 abc.txt 파일을 삭제하는 명령문", "del abc.txt"],
  ["Windows 기본 명령어 중 파일의 내용을 표시하는 명령어", "TYPE"],
  ["Windows 기본 명령어 중 TYPE의 기능", "파일의 내용을 표시함"],
  ["Windows에서 abc.txt 파일의 내용을 표시하는 명령문", "type abc.txt"],
  ["Windows 기본 명령어 중 파일의 이름을 변경하는 명령어", "REN"],
  ["Windows 기본 명령어 중 REN의 기능", "파일의 이름을 변경함"],
  ["Windows에서 abc.txt 파일의 이름을 123.txt로 변경하는 명령문", "ren abc.txt 123.txt"],
  ["Windows 기본 명령어 중 디렉터리를 생성하는 명령어", "MD"],
  ["Windows 기본 명령어 중 MD의 기능", "디렉터리를 생성함"],
  ["Windows에서 forder 디렉터리를 생성하는 명령문", "md forder"],
  ["Windows 기본 명령어 중 동일한 드라이브에서 디렉터리의 위치를 변경하는 명령어", "CD"],
  ["Windows 기본 명령어 중 CD의 기능", "동일한 드라이브에서 디렉터리의 위치를 변경함"],
  ["Windows에서 디렉터리의 위치를 forder로 변경하는 명령문", "cd forder"],
  ["Windows 기본 명령어 중 화면의 내용을 지우는 명령어", "CLS"],
  ["Windows 기본 명령어 중 CLS의 기능", "화면의 내용을 지움"],
  ["Windows 기본 명령어 중 파일의 속성을 변경하는 명령어", "ATTRIB"],
  ["Windows 기본 명령어 중 ATTRIB의 기능", "파일의 속성을 변경함"],
  ["Windows에서 abc.txt의 파일 속성을 읽기 전용으로 변경하는 명령문", "attrib +r abc.txt"],
  ["Windows 기본 명령어 중 파일에서 문자열을 찾는 명령어", "FIND"],
  ["Windows 기본 명령어 중 FIND의 기능", "파일에서 문자열을 찾음"],
  ["Windows에서 abc.txt에서 \"123\"이 포함된 문자열을 찾는 명령문", "find \"123\" abc.txt"],
  ["Windows 기본 명령어 중 디스크의 상태를 점검하는 명령어", "CHKDSK"],
  ["Windows 기본 명령어 중 CHKDSK의 기능", "디스크의 상태를 점검함"],
  ["Windows 기본 명령어 중 디스크 표면을 트랙과 섹터로 나누어 초기화하는 명령어", "FORMAT"],
  ["Windows 기본 명령어 중 FORMAT의 기능", "디스크 표면을 트랙과 섹터로 나누어 초기화함"],
  ["Windows에서 c 드라이브를 초기화하는 명령문", "format c:"],
  ["Windows 기본 명령어 중 파일을 이동하는 명령어", "MOVE"],
  ["Windows 기본 명령어 중 MOVE의 기능", "파일을 이동함"],
  ["Windows에서 abc.txt 파일을 forder 디렉터리로 이동하는 명령문", "move abc.txt forder"],
  ["UNIX/LINUX 기본 명령어 중 파일 내용을 화면에 표시하는 명령어", "cat"],
  ["UNIX/LINUX 기본 명령어 중 cat의 기능", "파일 내용을 화면에 표시함"],
  ["UNIX/LINUX에서 abc.txt 파일 내용을 화면에 표시하는 명령문", "cat abc.txt"],
  ["UNIX/LINUX 기본 명령어 중 디렉터리의 위치를 변경하는 명령어", "cd"],
  ["UNIX/LINUX 기본 명령어 중 cd의 기능", "디렉터리의 위치를 변경함"],
  ["UNIX/LINUX에서 forder 디렉터리로 이동하는 명령문", "cd forder"],
  ["UNIX/LINUX 기본 명령어 중 파일의 보호 모드를 설정하여 파일의 사용 허가를 지정하는 명령어", "chmod"],
  ["UNIX/LINUX 기본 명령어 중 chmod의 기능", "파일의 보호 모드를 설정하여 파일의 사용 허가를 지정함"],
  ["UNIX/LINUX에서 사용자에게 abc.txt 파일의 읽기, 쓰기, 실행 권한을 추가하는 명령문", "chmod u+rwx abc.txt"],
  ["UNIX/LINUX에서 그룹에게 abc.txt 파일의 읽기, 쓰기, 실행 권한을 삭제하는 명령문", "chmod g-rwx abc.txt"],
  ["UNIX/LINUX에서 기타 사용자에게 abc.txt 파일의 읽기, 쓰기, 실행 권한을 부여하는 명령문", "chmod o=rwx abc.txt"],
  ["UNIX/LINUX 기본 명령어 중 파일 소유자와 그룹을 변경하는 명령어", "chown"],
  ["UNIX/LINUX 기본 명령어 중 chown의 기능", "파일 소유자와 그룹을 변경함"],
  ["UNIX/LINUX에서 abc.txt 파일의 소유자를 member1로 변경하는 명령문", "chown member1 abc.txt"],
  ["UNIX/LINUX 기본 명령어 중 파일을 복사하는 명령어", "cp"],
  ["UNIX/LINUX 기본 명령어 중 cp의 기능", "파일을 복사함"],
  ["UNIX/LINUX에서 abc.txt 파일을 forder 디렉터리에 abc2.txt로 이름을 변경하여 복사하는 명령문", "cp abc.txt forder/abc2.txt"],
  ["UNIX/LINUX 기본 명령어 중 파일을 삭제하는 명령어", "rm"],
  ["UNIX/LINUX 기본 명령어 중 rm의 기능", "파일을 삭제함"],
  ["UNIX/LINUX에서 abc.txt를 삭제하는 명령문", "rm abc.txt"],
  ["UNIX/LINUX 기본 명령어 중 파일을 찾는 명령어", "find"],
  ["UNIX/LINUX 기본 명령어 중 find의 기능", "파일을 찾음"],
  ["UNIX/LINUX에서 abc.txt 파일을 찾는 명령문", "find abc.txt"],
  ["UNIX/LINUX 기본 명령어 중 파일 시스템을 검사하고 보수하는 명령어", "fsck"],
  ["UNIX/LINUX 기본 명령어 중 fsck의 기능", "파일 시스템을 검사하고 보수함"],
  ["UNIX/LINUX에서 /dev/sda11에 기록된 모든 파일 시스템을 검사하고 보수하는 명령문", "fsck /dev/sda1"],
  ["UNIX/LINUX 기본 명령어 중 PID(프로세스 고유 번호)를 이용하여 프로세스를 종료하는 명령어", "kill"],
  ["UNIX/LINUX 기본 명령어 중 kill의 기능", "PID(프로세스 고유 번호)를 이용하여 프로세스를 종료함"],
  ["UNIX/LINUX에서 PID가 1234인 프로세스를 종료하는 명령문", "kill 1234"],
  ["UNIX/LINUX 기본 명령어 중 새로운 프로세스를 생성하는 명령어", "fork"],
  ["UNIX/LINUX 기본 명령어 중 fork의 기능", "새로운 프로세스를 생성함"],
  ["UNIX/LINUX 기본 명령어 중 프로세스의 이름을 이용하여 프로세스를 종료하는 명령어", "killall"],
  ["UNIX/LINUX 기본 명령어 중 killall의 기능", "프로세스의 이름을 이용하여 프로세스를 종료함"],
  ["UNIX/LINUX에서 프로세스 이름이 abc인 모든 프로세스를 종료하는 명령문", "killall abc"],
  ["UNIX/LINUX 기본 명령어 중 현재 디렉터리의 파일 목록을 표시하는 명령어", "ls"],
  ["UNIX/LINUX 기본 명령어 중 ls의 기능", "현재 디렉터리의 파일 목록을 표시함"],
  ["UNIX/LINUX 기본 명령어 중 디렉터리를 생성하는 명령어", "mkdir"],
  ["UNIX/LINUX 기본 명령어 중 mkdir의 기능", "디렉터리를 생성함"],
  ["UNIX/LINUX에서 forder 디렉터리를 생성하는 명령문", "mkdir forder"],
  ["UNIX/LINUX 기본 명령어 중 디렉터리를 삭제하는 명령어", "rmdir"],
  ["UNIX/LINUX 기본 명령어 중 rmdir의 기능", "디렉터리를 삭제함"],
  ["UNIX/LINUX에서 forder 디렉터리를 삭제하는 명령문", "rmdir forder"],
  ["UNIX/LINUX 기본 명령어 중 파일을 이동하는 명령어", "mv"],
  ["UNIX/LINUX 기본 명령어 중 mv의 기능", "파일을 이동함"],
  ["UNIX/LINUX에서 abc.txt 파일을 forder 디렉터리에 abc2.txt로 이름을 변경하여 이동하는 명령문", "mv abc.txt forder/abc2.txt"],
  ["UNIX/LINUX 기본 명령어 중 현재 실행중인 프로세스를 표시하는 명령어", "ps"],
  ["UNIX/LINUX 기본 명령어 중 ps의 기능", "현재 실행중인 프로세스를 표시함"],
  ["UNIX/LINUX 기본 명령어 중 현재 작업중인 디렉터리 경로를 화면에 표시하는 명령어", "pwd"],
  ["UNIX/LINUX 기본 명령어 중 pwd의 기능", "현재 작업중인 디렉터리 경로를 화면에 표시함"],
  ["UNIX/LINUX 기본 명령어 중 시스템의 프로세스와 메모리 사용 현황을 표시하는 명령어", "top"],
  ["UNIX/LINUX 기본 명령어 중 top의 기능", "시스템의 프로세스와 메모리 사용 현황을 표시함"],
  ["UNIX/LINUX 기본 명령어 중 현재 시스템에 접속해 있는 사용자를 표시하는 명령어", "who"],
  ["UNIX/LINUX 기본 명령어 중 who의 기능", "현재 시스템에 접속해 있는 사용자를 표시함"],
  ["UNIX/LINUX에서 'batch.sh' 파일에 대해 소유자와 그룹에게는 전체 권한을, 기타 사용자에게는 읽기와 실행 권한만 부여하는 명령문을 8진법 숫자를 이용하여 작성하기", "chmod 775 batch.sh"],
];