export const QA014 = [
    ["송/수신 측 간의 전송 경로 중에서 최적 패킷 교환 경로를 결정하는 기능", "경로 제어", "Routing"],
    ["경로 제어표(Routing Table)를 참조해서 이루어지며 라우터에 의해 수행되는 기능", "경로 제어", "Routing"],
    ["성능 기준, 경로의 결정 시간과 장소, 정보 발생지, 경로 정보의 갱신 시간은 어떤 기능의 요소인가", "경로 제어", "Routing"],
    ["경로 제어 프로토콜(Routing Protocol) 중 하나의 자율 시스템(AS) 내의 라우팅에 사용되는 프로토콜", "내부 게이트웨이 프로토콜", "IGP", "Interior Gateway Protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 현재 가장 널리 사용되는 라우팅 프로토콜로, 거리 벡터 라우팅 프로토콜이라고도 불리는 프로토콜", "RIP", "Routing Information Protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 최단 경로 탐색에 Bellman-Ford 알고리즘을 사용하는 프로토콜", "RIP", "Routing Information Protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 소규모 동종의 네트워크(자율 시스템, AS) 내에서 효율적인 방법인 프로토콜", "RIP", "Routing Information Protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 최대 홉(Hop) 수를15로 제한하므로 15 이상의 경우에는 도달할 수 없는 네트워크를 의미하여 대규모 네트워크에선 사용할 수 없는 프로토콜", "RIP", "Routing Information Protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 라우팅 정보를 30초마다 네트워크 내의 모든 라우터에 알리며, 180초 이내에 새로운 라우팅 정보가 수신되지 않으면 해당 경로를 이상 상태로 간주하는 프로토콜", "RIP", "Routing Information Protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 RIP의 단점을 해결하여 새로운 기능을 지원하는 인터넷 프로토콜로, 대규모 네트워크에서 많이 사용됨", "OSPF", "Open Shortest Path First protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 인터넷 망에서 이용자가 최단 경로를 선정할 수 있도록 라우팅 정보에 노드 간의 거리 정보, 링크 상태 정보를 실시간으로 반영하여 최단 경로로 라우팅을 지원하는 프로토콜", "OSPF", "Open Shortest Path First protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 최단 경로 탐색에 다익스트라(Dijkstra) 알고리즘을 사용하는 프로토콜", "OSPF", "Open Shortest Path First protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 라우팅 정보에 변화가 생길 경우 변화된 정보만 네트워크 내의 모든 라우터에 알리는 프로토콜", "OSPF", "Open Shortest Path First protocol"],
    ["IGP(Interior Gateway Protocol)의 한 종류이며 하나의 자율 시스템(AS)에서 동작하면서 내부 라우팅 프로토콜의 그룹에 도달하는 프로토콜", "OSPF", "Open Shortest Path First protocol"],
    ["자율 시스템(AS) 간의 라우팅, 즉 게이트웨이 간의 라우팅에 사용되는 프로토콜", "EGP", "Exterior Gateway Protocol"],
    ["자율 시스템(AS) 간의 라우팅 프로토콜로 EGP의 단점을 보완하기 위해 만들어진 프로토콜", "BGP", "Border Gateway Protocol"],
    ["초기에 BGP 라우터들이 연결될 때에는 전체 경로 제어표(라우팅 테이블)를 교환하고, 이후에는 변화된 정보만을 교환하는 라우팅 프로토콜", "BGP", "Border Gateway Protocol"],
    ["네트워크 보호, 성능 유지, 네트워크 자원의 효율적인 이용을 위해 전송되는 패킷의 흐름 또는 그 양을 조절하는 기능", "트래픽 제어", "Traffic Control"],
    ["전송되는 패킷의 흐름 또는 그 양을 조절하는 기능으로, 종류로 흐름 제어, 폭주(혼합) 제어, 교착상태 방지가 있는 기능", "트래픽 제어", "Traffic Control"],
    ["네트워크 내의 원활한 흐름을 위해 송/수신 측 사이에 전송되는 패킷의 양이나 속도를 규제하는 기능", "흐름 제어", "Flow Control"],
    ["송/수신 측 사이의 패킷 수를 제어 하는 기능", "흐름 제어", "Flow Control"],
    ["흐름 제어(Flow Control)의 기법 중 수신 측의 확인 신호(ACK)를 받은 후에 다음 패킷을 전송하는 방식", "정지-대기", "Stop-and-Wait"],
    ["흐름 제어(Flow Control)의 기법 중 한 번에 하나의 패킷만을 전송할 수 있는 방식", "정지-대기", "Stop-and-Wait"],
    ["흐름 제어(Flow Control)의 기법 중 확인 신호, 즉 수신 통지를 이용하여 송신 데이터의 양을 조절하는 방식", "슬라이딩 윈도우", "Sliding Window"],
    ["흐름 제어(Flow Control)의 기법 중 수신 측의 확인 신호를 받지 않더라도 미리 정해진 패킷의 수만큼 연속적으로 전송하는 방식으로, 한 번에 여러 개의 패킷을 전송할 수 있어 전송 효율이 좋은 기법", "슬라이딩 윈도우", "Sliding Window"],
    ["흐름 제어(Flow Control)과 관련된 용어 중 송신 측은 수신 측으로부터 확인 신호(ACK) 없이도 보낼 수 있는 최대치를 미리 약속받는데, 이 패킷의 최대치를 의미하는 용어", "윈도우 크기", "Window Size"],
    ["네트워크 내의 패킷 수를 조절하여 네트워크의 오버플로(Overflow)를 방지하는 기능", "폭주 제어", "Congestion Control"],
    ["윈도우의 크기를 2배씩 지수적으로 증가시켜 초기에는 느리지만 갈수록 빨라지며, 전송 데이터의 크기가 임계 값에 도달하면 혼잡 회피 단계로 넘어가는 폭주 제어의 기법", "느린 시작", "Slow Start"],
    ["느린 시작(Slow Start)의 지수적 증가가 임계 값에 도달되면 혼잡으로 간주하고 회피를 위해 윈도우의 크기를 1씩 선형적으로 증가시켜 혼잡을 예방하는 방식", "혼잡 회피", "Congestion Avoidance"]
];