export const QA012 = [
    ["서로 다른 기기들 간의 데이터 교환을 원활하게 수행할 수 있도록 표준화시켜 놓은 통신 규약", "프로토콜", "Protocol"],
    ["1965년 톰 마릴(Tom Maril)이 컴퓨터가 메시지를 전달하고, 메시지가 제대로 도착했는지 확인하며, 도착하지 않았을 경우 메시지를 재전송하는 일련의 방법으로 '기술적 은어'라는 뜻을 가진 용어", "프로토콜", "Protocol"],
    ["서로 다른 기기들 간의 데이터 교환을 원활하게 수행할 수 있도록 표준화시켜 놓은 통신 규약의 영어 풀네임(Full-Name)", "Protocol"],
    ["프로토콜의 기본 요소 3가지", "구문, 의미, 시간", "Syntax, Semantics, Timing"],
    ["프로토콜의 기본 요소 중 전송하고자 하는 데이터의 형식, 부호화, 신호 레벨 등을 규정하는 용어", "구문", "Syntax"],
    ["프로토콜의 기본 요소 중 전송하고자 하는 데이터의 형식, 부호화, 신호 레벨 등을 규정하는 용어의 영어 풀네임(Full-Name)", "Syntax"],
    ["프로토콜의 기본 요소 중 두 기기 간의 효율적이고 정확한 정보 전송을 위한 협조 사항과 오류 관리를 위한 제어 정보를 규정하는 용어", "의미", "Semantics"],
    ["프로토콜의 기본 요소 중 두 기기 간의 효율적이고 정확한 정보 전송을 위한 협조 사항과 오류 관리를 위한 제어 정보를 규정하는 용어의 영어 풀네임(Full-Name)", "Semantics"],
    ["프로토콜의 기본 요소 중 두 기기 간의 통신 속도, 메시지의 순서 제어 등을 규정하는 용어", "시간", "Timing"],
    ["프로토콜의 기본 요소 중 두 기기 간의 통신 속도, 메시지의 순서 제어 등을 규정하는 용어의 영어 풀네임(Full-Name)", "Timing"],
    ["두 개체 간에 합의된 약속이란 의미로, 단편화와 재결합, 캡슐화, 흐름 제어, 오류 제어, 동기화, 순서 제어, 주소 지정, 다중화, 경로 제어, 전송 서비스 등의 기능을 제공하는 것", "프로토콜", "Protocol"],
    ["인터넷에 연결된 서로 다른 기종의 컴퓨터들이 데이터를 주고받을 수 있도록 하는 표준 프로토콜", "TCP/IP"],
    ["OSI 7계층의 전송 계층에 해당하며, 가상 회선 방식을 기반으로 하는 연결형 서비스를 제공하는 프로토콜", "TCP", "Transmission Control Protocol"],
    ["OSI 7계층의 전송 계층에 해당하며, 패킷의 다중화, 순서 제어, 오류 제어, 흐름 제어 기능을 제공하는 프로토콜", "TCP", "Transmission Control Protocol"],
    ["OSI 7계층의 네트워크 계층에 해당하며, 데이터그램 방식을 기반으로 하는 비연결형 서비스를 제공하는 프로토콜", "IP", "Internet Protocol"],
    ["OSI 7계층의 네트워크 계층에 해당하며, 패킷의 분해/조립, 주소 지정, 경로 선택 기능을 제공하는 프로토콜", "IP", "Internet Protocol"],
    ["응용 계층, 전송 계층, 인터넷 계층, 네트워크 액세스 계층의 구조로 이루어진 표준 프로토콜", "TCP/IP"],
    ["응용 프로그램 간의 데이터 송/수신을 제공하며 OSI 7계층의 응용, 표현, 세션 계층에 해당하는 TCP/IP의 계층", "응용 계층"],
    ["TELNET, FTP, SMTP, SNMP, UNS, HTTP 등이 해당하는 TCP/IP의 계층", "응용 계층"],
    ["호스트들 간의 신뢰성 있는 통신을 제공하며 OSI 7계층의 전송 계층에 해당하는 TCP/IP의 계층", "전송 계층"],
    ["TCP, UDP, RTCP 등이 해당하는 TCP/IP의 계층", "전송 계층"],
    ["데이터 전송을 위한 주소 지정, 경로 설정을 제공하며 OSI 7계층의 네트워크 계층에 해당하는 TCP/IP의 계층", "인터넷 계층"],
    ["IP, ICMP, IGMP, ARP, RARP 등이 해당하는 TCP/IP의 계층", "인터넷 계층"],
    ["실제 데이터(프레임)을 송/수신하는 역할로 OSI 7계층의 데이터 링크, 물리 계층에 해당하는 TCP/IP의 계층", "네트워크 액세스 계층"],
    ["Ethernet, IEEE 802, HDLC, X.25, RS-232C 등이 해당하는 TCP/IP의 계층", "네트워크 액세스 계층"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 컴퓨터와 컴퓨터 또는 컴퓨터와 인터넷 사이에서 파일을 주고받을 수 있도록 하는 원격 파일 전송 프로토콜", "FTP", "File Transfer Protocol"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 컴퓨터와 컴퓨터 또는 컴퓨터와 인터넷 사이에서 파일을 주고받을 수 있도록 하는 원격 파일 전송 프로토콜의 영어 풀네임(Full-Name)", "File Transfer Protocol"],
    ["FTP(File Tranfer Protocol)이 해당하는 TCP/IP 계층", "응용 계층"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 전자 우편을 교환하는 서비스", "SMTP", "Simple Mail Transfer Protocol"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 전자 우편을 교환하는 서비스의 영어 풀네임(Full-Name)", "Simple Mail Transfer Protocol"],
    ["SMTP(Simple Mail Transfer Protocol)이 해당하는 TCP/IP 계층", "응용 계층"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 멀리 떨어져 있는 컴퓨터에 접속하여 자신의 컴퓨터처럼 사용할 수 있도록 해주는 서비스", "TELNET"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 프로그램을 실행하는 등 시스템 관리 작업을 할 수 있는 가상의 터미널(Virtual Terminal) 기능을 수행하는 서비스", "TELNET"],
    ["TELNET이 해당하는 TCP/IP 계층", "응용 계층"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 TCP/IP의 네트워크 관리 프로토콜로, 라우터나 허브 등 네트워크 기기의 네트워크 정보를 네트워크 관리 시스템에 보내는데 사용되는 표준 통신 규약", "SNMP", "Simple Network Management Protocol"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 TCP/IP의 네트워크 관리 프로토콜로, 라우터나 허브 등 네트워크 기기의 네트워크 정보를 네트워크 관리 시스템에 보내는데 사용되는 표준 통신 규약의 영어 풀네임(Full-Name)", "Simple Network Management Protocol"],
    ["SNMP(Simple Network Management Protocol)가 해당하는 TCP/IP 계층", "응용 계층"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 도메인 네임을 IP 주소로 매핑(Mapping)하는 시스템", "DNS", "Domain Name System"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 도메인 네임을 IP 주소로 매핑(Mapping)하는 시스템의 영어 풀네임(Full-Name)", "Domain Name System"],
    ["DNS(Domain Name System)가 해당하는 TCP/IP 계층", "응용 계층"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 월드 와이드 웹(WWW)에서 HTML 문서를 송수신하기 위한 표준 프로토콜", "HTTP", "HyperText Transfer Protocol"],
    ["TCP/IP 계층 중 응용 계층에 해당하며 월드 와이드 웹(WWW)에서 HTML 문서를 송수신하기 위한 표준 프로토콜의 영어 풀네임(Full-Name)", "HyperText Transfer Protocol"],
    ["HTTP(HyperText Transfer Protocol)가 해당하는 TCP/IP 계층", "응용 계층"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 양방향 연결(Full Duplex Connection)형 서비스와 가상 회선 연결(Virtual Circuit Connection) 형태의 서비스를 제공하는 프로토콜", "TCP", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 양방향 연결(Full Duplex Connection)형 서비스와 가상 회선 연결(Virtual Circuit Connection) 형태의 서비스를 제공하는 프로토콜의 영어 풀네임(Full-Name)", "Transmission Control Protocol"],
    ["TCP(Transmission Control Protocol)가 해당하는 TCP/IP 계층", "전송 계층"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 스트림 위주의 전달(패킷 단위)을 하며 신뢰성 있는 경로를 확립하고 메시지 전송을 감독하는 프로토콜", "TCP", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 스트림 위주의 전달(패킷 단위)을 하며 신뢰성 있는 경로를 확립하고 메시지 전송을 감독하는 프로토콜의 영어 풀네임(Full-Name)", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 순서 제어, 오류 제어, 흐름 제어 기능을 하며 패킷의 분실, 손상, 지연이나 순서가 틀린 것 등이 발생할 때 투명성이 보장되는 통신을 제공하는 프로토콜", "TCP", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 순서 제어, 오류 제어, 흐름 제어 기능을 하며 패킷의 분실, 손상, 지연이나 순서가 틀린 것 등이 발생할 때 투명성이 보장되는 통신을 제공하는 프로토콜의 영어 풀네임(Full-Name)", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 헤더는 기본적으로 20Byte에서 60Byte까지 사용할 수 있는데, 선택적으로 40Byte를 더 추가할 수 있어서 최대 100Byte까지 크기를 확장할 수 있는 프로토콜", "TCP", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 헤더는 기본적으로 20Byte에서 60Byte까지 사용할 수 있는데, 선택적으로 40Byte를 더 추가할 수 있어서 최대 100Byte까지 크기를 확장할 수 있는 프로토콜의 영어 풀네임(Full-Name)", "Transmission Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 데이터 전송 전에 연결을 설정하지 않는 비연결형 서비스를 제공하며 실시간 전송에 유리하며, 신뢰성보다는 속도가 중요시되는 네트워크에 사용되는 프로토콜", "UDP", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 데이터 전송 전에 연결을 설정하지 않는 비연결형 서비스를 제공하며 실시간 전송에 유리하며, 신뢰성보다는 속도가 중요시되는 네트워크에 사용되는 프로토콜의 영어 풀네임(Full-Name)", "User Datagram Protocol"],
    ["UDP(User Datagram Protocol)이 해당하는 TCP/IP 계층", "전송 계층"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 TCP에 비해 상대적으로 단순한 헤더 구조를 가지고 있어서 오버헤드가 적고, 흐름 제어나 순서 제어가 없어 전송 속도가 빠른 프로토콜", "UDP", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 TCP에 비해 상대적으로 단순한 헤더 구조를 가지고 있어서 오버헤드가 적고, 흐름 제어나 순서 제어가 없어 전송 속도가 빠른 프로토콜의 영어 풀네임(Full-Name)", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 고속의 안정성 있는 전송 매체를 사용하며 빠른 속도를 필요로 하는 경우, 동시에 여러 사용자에게 데이터를 전달할 경우, 정기적으로 반복해서 전송할 경우에 사용하는 프로토콜", "UDP", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 고속의 안정성 있는 전송 매체를 사용하며 빠른 속도를 필요로 하는 경우, 동시에 여러 사용자에게 데이터를 전달할 경우, 정기적으로 반복해서 전송할 경우에 사용하는 프로토콜의 영어 풀네임(Full-Name)", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 헤더에 Source Port Number, Destination Port Number, Length, Checksum 등이 포함된 프로토콜", "UDP", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 헤더에 Source Port Number, Destination Port Number, Length, Checksum 등이 포함된 프로토콜의 영어 풀네임(Full-Name)", "User Datagram Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 RTP(Real-time Transport Protocol) 패킷의 전송 품질을 제어하기 위한 제어 프로토콜", "RTCP", "Real-Time Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 RTP(Real-time Transport Protocol) 패킷의 전송 품질을 제어하기 위한 제어 프로토콜의 영어 풀네임(Full-Name)", "Real-Time Control Protocol"],
    ["RTCP(Real-Time Control Protocol)가 해당하는 TCP/IP 계층", "전송 계층"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 세션에 참여한 각 참여자들에게 주기적으로 제어 정보를 전송하며 하위 프로토콜은 데이터 패킷과 제어 패킷의 다중화를 제공하는 프로토콜", "RTCP", "Real-Time Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 세션에 참여한 각 참여자들에게 주기적으로 제어 정보를 전송하며 하위 프로토콜은 데이터 패킷과 제어 패킷의 다중화를 제공하는 프로토콜의 영어 풀네임(Full-Name)", "Real-Time Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 데이터 전송을 모니터링하고 최소한의 제어와 인증 기능만을 제공하며 패킷이 항상 32비트의 경계로 끝나는 프로토콜", "RTCP", "Real-Time Control Protocol"],
    ["TCP/IP 계층 중 전송 계층에 해당하며 데이터 전송을 모니터링하고 최소한의 제어와 인증 기능만을 제공하며 패킷이 항상 32비트의 경계로 끝나는 프로토콜의 영어 풀네임(Full-Name)", "Real-Time Control Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 전송할 데이터에 주소를 지정하고, 경로를 설정하는 기능을 하는 프로토콜", "IP", "Internet Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 전송할 데이터에 주소를 지정하고, 경로를 설정하는 기능을 하는 프로토콜의 영어 풀네임(Full-Name)", "Internet Protocol"],
    ["IP(Internet Protocol)가 해당하는 TCP/IP 계층", "인터넷 계층"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 비연결형인 데이터그램 방식을 사용하는 것으로 신뢰성이 보장되지 않는 프로토콜", "IP", "Internet Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 비연결형인 데이터그램 방식을 사용하는 것으로 신뢰성이 보장되지 않는 프로토콜의 영어 풀네임(Full-Name)", "Internet Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 IP와 조합하여 통신중에 발생하는 오류의 처리와 전송 경로 변경 등을 위한 제어 메시지를 관리하는 역할을 하며 헤더는 8Byte로 구성된 프로토콜", "인터넷 제어 메시지 프로토콜", "ICMP", "Internet Control Message Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 IP와 조합하여 통신중에 발생하는 오류의 처리와 전송 경로 변경 등을 위한 제어 메시지를 관리하는 역할을 하며 헤더는 8Byte로 구성된 프로토콜의 영어 풀네임(Full-Name)", "Internet Control Message Protocol"],
    ["ICMP(Internet Control Message Protocol)가 해당하는 TCP/IP 계층", "인터넷 계층"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 멀티캐스트를 지원하는 호스트나 라우터 사이에서 멀티캐스트 그룹 유지를 위해 사용되는 프로토콜", "인터넷 그룹 관리 프로토콜", "IGMP", "Internet Group Management Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 멀티캐스트를 지원하는 호스트나 라우터 사이에서 멀티캐스트 그룹 유지를 위해 사용되는 프로토콜의 영어 풀네임(Full-Name)", "Internet Group Management Protocol"],
    ["IGMP(Internet Group Management Protocol)가 해당하는 TCP/IP 계층", "인터넷 계층"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 호스트의 IP 주소를 호스트와 연결된 네트워크 접속 장치의 물리적 주소(MAC Address)로 바꿔주는 프로토콜", "주소 분석 프로토콜", "ARP", "Address Resolution Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 호스트의 IP 주소를 호스트와 연결된 네트워크 접속 장치의 물리적 주소(MAC Address)로 바꿔주는 프로토콜의 영어 풀네임(Full-Name)", "Address Resolution Protocol"],
    ["ARP(Address Resolution Protocol)가 해당하는 TCP/IP 계층", "인터넷 계층"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 물리적 주소를 IP 주소로 변환하는 기능을 하는 프로토콜", "RARP", "Reverse Address Resolution Protocol"],
    ["TCP/IP 계층 중 인터넷 계층에 해당하며 물리적 주소를 IP 주소로 변환하는 기능을 하는 프로토콜의 영어 풀네임(Full-Name)", "Reverse Address Resolution Protocol"],
    ["RARP(Reverse Address Resolution Protocol)이 해당하는 TCP/IP 계층", "인터넷 계층"],
    ["TCP/IP 계층 중 네트워크 액세스 계층에 해당하며 CSMA.CD 방식의 LAN", "Ethernet", "IEEE 802.3"],
    ["Ethernet이 해당하는 TCP/IP 계층", "네트워크 액세스 계층"],
    ["TCP/IP 계층 중 네트워크 액세스 계층에 해당하며 LAN을 위한 표준 프로토콜", "IEEE 802"],
    ["IEEE 802가 해당하는 TCP/IP 계층", "네트워크 액세스 계층"],
    ["TCP/IP 계층 중 네트워크 액세스 계층에 해당하며 비트 위주의 데이터 링크 제어 프로토콜", "HDLC"],
    ["HDLC가 해당하는 TCP/IP 계층", "네트워크 액세스 계층"],
    ["TCP/IP 계층 중 네트워크 액세스 계층에 해당하며 패킷 교환망을 통한 DTE와 DCE 간의 인터페이스를 제공하는 프로토콜", "X.25"],
    ["X.25가 해당하는 TCP/IP 계층", "네트워크 액세스 계층"],
    ["TCP/IP 계층 중 네트워크 액세스 계층에 해당하며 공중 전화 교환망(PSTN)을 통한 DTE와 DCE 간의 인터페이스를 제공하는 프로토콜", "RS-232C"],
    ["RS-232C가 해당하는 TCP/IP 계층", "네트워크 액세스 계층"],
    ["연결형 통신에서 주로 사용되는 방식으로, 출발지와 목적지의 전송 경로를 미리 연결하여 논리적으로 고정한 후 통신하는 방식", "가상 회선"],
    ["비연결형 통신에서 주로 사용되는 방식으로, 사전에 접속 절차를 수행하지 않고 헤더에 출발지와 목적지까지의 경로 지정을 위한 충분한 정보를 붙여서 개별적으로 전달하는 방식", "데이터그램"]
];