export const QA044 = [
	["DB 구조, 데이터 형식, 접근 방식 등 DB를 구축하거나 수정할 목적으로 사용하는 언어", "데이터 정의어", "DDL", "Data Define Language"],
	["데이터 정의어(DDL)을 번역한 결과는 (\0\0\0)라는 특별한 파일에 여러 개의 테이블로 저장됨", "데이터 사전", "Data Dictionary"],
	["DDL의 3가지 유형 중 SCHEMA, DOMAIN, TABLE, VIEW, INDEX를 정의하는 명령어", "CREATE"],
	["DDL의 3가지 유형 중 TABLE에 대한 정의를 변경하는 데 사용하는 명령어", "ALTER"],
	["DDL의 3가지 유형 중 SCHEMA, DOMAIN, TABLE, VIEW, INDEX를 삭제하는 명령어", "DROP"],
	["스키마를 정의하는 명령문", "CREATE SCHEMA"],
	["스키마를 정의하는 명령문의 표기 형식은 \nCREATE SCHEMA 스키마명 (\0\0\0) 사용자_id; 이다.\n괄호 안에 들어갈 단어는?", "AUTHORIZATION"],
	["도메인을 정의하는 명령문", "CREATE DOMAIN"],
	["도메인을 정의하는 명령문의 표기 형식은 \nCREATE DOMAIN 도메인명 [AS] 데이터_타입 \n[(\0\0\0) 기본값] \n[CONSTRAINT 제약조건명 CHECK (범위값)]; 이다.\n괄호 안에 들어갈 단어는?", "DEFAULT"], 
	["도메인을 정의하는 명령문의 표기 형식은 \nCREATE DOMAIN 도메인명 [AS] 데이터_타입 \n[DEFAULT 기본값] \n[(\0\0\0) 제약조건명 CHECK (범위값)]; 이다. \n괄호 안에 들어갈 단어는?", "CONSTRAINT"],
	["테이블을 정의하는 명령문", "CREATE TABLE"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [(\0\0\0)], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[ON UPDATE 옵션] \n[, CONSTRAINT 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 NULL을 허용하지 않겠다는 명령어는?", "NOT NULL"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, (\0\0\0)(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[ON UPDATE 옵션] \n[, CONSTRAINT 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 기본키로 사용할 속성을 지정하는 명령어는?", "PRIMARY KEY"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, (\0\0\0)(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[ON UPDATE 옵션] \n[, CONSTRAINT 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 대체키로 사용할 속성을 지정하며, 중복된 값을 가질 수 없다는 속성을 지정하는 명령어는?", "UNIQUE"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, (   ①   )(외래키_속성명, ...) (   ②   ) 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[ON UPDATE 옵션] \n[, CONSTRAINT 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 외래키로 사용할 속성을 지정하는 명령어는?", "FOREIGN KEY, REFERENCES"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[(\0\0\0) 옵션] \n[ON UPDATE 옵션] \n[, CONSTRAINT 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 참조 테이블의 튜플이 삭제되었을 때 기본 테이블에 취해야 할 사항을 지정하는 명령어는?", "ON DELETE"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[(\0\0\0) 옵션] \n[, CONSTRAINT 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 참조 테이블의 참조 속성 값이 변경되었을 때 기본 테이블에 취해야 할 사항을 지정하는 명령어는?", "ON UPDATE"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[ON UPDATE 옵션] \n[, (\0\0\0) 제약조건명] [CHECK (조건식)]); 이다. \n괄호 안에 들어갈 제약 조건의 이름을 지정하는 명령어는?", "CONSTRAINT"],
	["테이블을 정의하는 명령문의 표기 형식은 \nCREATE TABLE 테이블명 (속성명 데이터 타입 \n[DEFAULT 기본값] [NOT NULL], ... \n[, PRIMARY KEY(기본키_속성명, ...)] \n[, UNIQUE(대체키_속성명, ...)] \n[, FOREIGN KEY(외래키_속성명, ...) REFERENCES 참조테이블(기본키_속성명, ...)] \n[ON DELETE 옵션] \n[ON UPDATE 옵션] \n[, CONSTRAINT 제약조건명] [(\0\0\0) (조건식)]); 이다. \n괄호 안에 들어갈 속성 값에 대한 제약 조건을 정의하는 명령어는?", "CHECK"],
	["뷰(View)를 정의하는 명령문", "CREATE VIEW"],
	["뷰(View)를 정의하는 명령문의 표기 형식은 \nCREATE VIEW 뷰명[(속성명[, 속성명, ...]) AS (\0\0\0)문; 이다. \n괄호 안에 들어갈 단어는?", "SELECT"],
	["인덱스를 정의하는 명령문", "CREATE INDEX"],
	["인덱스를 정의하는 명령문의 표기 형식은 \nCREATE [(\0\0\0)] INDEX 인덱스명 ON 테이블명(속성명 [ASC | DESC] [, 속성명 [ASC | DESC]]) [CLUSTER]; 이다. \n괄호 안에 들어갈 중복 값이 없는 속성으로 인덱스를 생성한다는 단어는?", "UNIQUE"],
	["인덱스를 정의하는 명령문의 표기 형식은 \nCREATE [UNIQUE] INDEX 인덱스명 ON 테이블명(속성명 [ASC | DESC] [, 속성명 [ASC | DESC]]) [(\0\0\0)]; 이다. \n괄호 안에 들어갈 인덱스가 클러스터드 인덱스로 설정되는 단어는?", "CLUSTER"],
	["테이블에 대한 정의를 변경하는 명령문", "ALTER TABLE"],
	["테이블에 대한 정의를 변경하는 명령문 중 새로운 속성(열)을 추가할 때 사용하는 명령문의 표기 형식은 \nALTER TABLE 테이블명 (\0\0\0) 속성명 데이터_타입 [DEFAULT '기본값']; 이다. \n괄호 안에 들어갈 단어는?", "ADD"],
	["테이블에 대한 정의를 변경하는 명령문 중 특정 속성의 Default 값을 변경할 때 사용하는 명령문의 표기 형식은 \nALTER TABLE 테이블명 (\0\0\0) 속성명 [SET DEFAULT '기본값']; 이다. \n괄호 안에 들어갈 단어는?", "ALTER"],
	["테이블에 대한 정의를 변경하는 명령문 중 특정 속성을 삭제할 때 사용하는 명령문의 표기 형식은 \nALTER TABLE 테이블명 (\0\0\0) 속성명 [CASCADE]; 이다. \n괄호 안에 들어갈 단어는?", "DROP COLUMN"],
	["스키마, 도메인, 기본 테이블, 뷰 테이블, 인덱스, 제약 조건 등을 제거하는 명령문", "DROP"]
];
