export const QA013 = [
    ["OSI의 2계층에 속하는 장비로 일반적으로 부르는 스위치(Switch)를 의미", "L2 스위치"],
    ["MAC 주소를 기반으로 프레임(패킷)을 전송하며, 동일 네트워크 간의 연결만 가능한 스위치(Switch)", "L2 스위치"],
    ["OSI의 3계층에 속하는 장비로, L2 스위치에 라우터 기능이 추가된 스위치(Switch)", "L3 스위치"],
    ["IP 주소를 기반으로 패킷을 전송하며 서로 다른 네트워크 간의 연결이 가능한 스위치(Switch)", "L3 스위치"],
    ["OSI의 4계층에 속하는 장비로, 로드밸런서가 달린 L3 스위치", "L4 스위치"],
    ["IP 주소 및 TCP/UDP를 기반으로 사용자들의 요구를 서버의 부하가 적은 곳에 배분하는 로드밸런싱 기능을 제공하는 스위치(Switch)", "L4 스위치"],
    ["OSI의 7계층에 속하는 장비로 IP 주소, TCP/UDP 포트 정보에 패킷 내용까지 참조하여 세밀하게 로드밸런싱하는 스위치(Switch)", "L7 스위치"],
    ["스위칭(Switch) 방식 3가지", "Store and Forwarding, Cut-through, Fragment Free"],
    ["스위칭(Switch) 방식 중 데이터를 모두 받은 후 스위칭하는 방식", "Store and Forwarding"],
    ["스위칭(Switch) 방식 중 데이터의 목적지 주소만을 확인한 후 바로 스위칭하는 방식", "Cut-through"],
    ["스위칭(Switch) 방식 중 Store and Forwarding과 Cut-through 방식의 장점을 결합한 방식", "Fragment Free"],
    ["네트워크들을 연결할 때 중추적 역할을 하는 네트워크", "백본", "Backbone"],
    ["백본에서 스위칭 역할을 하는 장비", "백본 스위치", "Backbone Switch"],
    ["모든 패킷이 지나가는 네트워크의 중심에 배치하며 대규모 트래픽을 처리할 때 사용하는 스위치", , "백본 스위치", "Backbone Switch"],
    ["주로 백본 스위치의 역할을 하는 스위치", "L3 스위치"],
    ["네트워크 구성 시 사용되는 모델의 한 종류로, 액세스 계층, 디스트리뷰션 계층, 코어 계층으로 나뉘는 모델", "Hierarchical 3 Layer 모델"],
    ["Hierarchical 3 Layer 모델 중 사용자가 네트워크에 접속할 때 최초로 연결되는 지점으로 사용자들로부터 오는 통신을 집약해서 디스트리뷰션 계층으로 전송하는 계층", "액세스 계층", "Access Layer"],
    ["Hierarchical 3 Layer 모델 중 이 계층에 배치되는 장비는 성능은 낮아도 되지만 포트 수는 사용자 수만큼 있어야 하며 L2 스위치를 사용하는 계층", "액세스 계층", "Access Layer"],
    ["Hierarchical 3 Layer 모델 중 액세스 계층의 장치들이 연결되는 지점으로 액세스 계층에서 오는 통신을 집약해서 코어 계층으로 전송하는 계층", "디스트리뷰션 계층", "Distribution Layer"],
    ["Hierarchical 3 Layer 모델 중 LAN 간에 라우팅 기능을 수행하며, 라우터, L3 스위치를 사용하는 계층", "디스트리뷰션 계층", "Distribution Layer"],
    ["Hierarchical 3 Layer 모델 중 디스트리뷰션 계층에서 오는 통신을 집약해 인터넷에 연결하는 계층으로, 백본 계층이라고도 하는 계층", "코어 계층", "Core Layer"],
    ["Hierarchical 3 Layer 모델 중 전자 우편, 인터넷 접속, 화상 회의 등의 기능을 수행하며 백본 스위치를 사용하는 계층", "코어 계층", "Core Layer"]
]